### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'overlay') at w2field.keyup (w2ui.es6.min.js:449:10111)

### ISSUE THREAD

**Issue by WillTheFarmer** [vitmalina/w2ui-starter-es6#7]
Error occurs when "list" control property openOnFocus is set to false and using keyboard arrow down key (40) to open dropdown list. Keyboard arrow key works properly IF first the dropdown is opened by mouse clicking on the dropdown arrow icon. Error happens every time when dropdown has not been opened first by 1) openOnFocus functionality or 2) Mouse Click on ArrowDown icon.

**Comment by WillTheFarmer-Will** [comment]
![Screenshot 2024-08-01 172658](https://github.com/user-attachments/assets/5b16eb36-6bb5-494c-9977-d39aa8ea67e8)
